name: lt316-admin

services:
  web:
    extends:
      file: infra/compose/dev.yml
      service: web

  asset-pipeline:
    extends:
      file: infra/compose/dev.yml
      service: asset-pipeline

volumes:
  web_node_modules:
  web_next:
  asset_pipeline_node_modules:
