import type { MaterialLaserCapability } from "./types.ts";

const STAINLESS_MOPA_COLORS = [
  {
    id: "ss-oxide-light",
    label: "Silver / Light",
    processFamily: "oxide-color",
    targetHex: "#c0c0c0",
    requiresMopa: true,
    basePresetId: "mopa-steel-silver-20w",
  },
  {
    id: "ss-oxide-gold",
    label: "Gold / Yellow",
    processFamily: "oxide-color",
    targetHex: "#c89610",
    requiresMopa: true,
    basePresetId: "mopa-steel-gold-20w",
  },
  {
    id: "ss-oxide-orange",
    label: "Orange / Bronze",
    processFamily: "oxide-color",
    targetHex: "#b86820",
    requiresMopa: true,
    basePresetId: "mopa-steel-orange-20w",
  },
  {
    id: "ss-oxide-red",
    label: "Red",
    processFamily: "oxide-color",
    targetHex: "#cc3300",
    requiresMopa: true,
    basePresetId: "mopa-steel-red-20w",
  },
  {
    id: "ss-oxide-purple",
    label: "Purple / Violet",
    processFamily: "oxide-color",
    targetHex: "#7722bb",
    requiresMopa: true,
    basePresetId: "mopa-steel-purple-20w",
  },
  {
    id: "ss-oxide-dark-blue",
    label: "Dark Blue",
    processFamily: "oxide-color",
    targetHex: "#002299",
    requiresMopa: true,
    basePresetId: "mopa-steel-darkblue-20w",
  },
  {
    id: "ss-oxide-blue",
    label: "Bright Blue",
    processFamily: "oxide-color",
    targetHex: "#2244cc",
    requiresMopa: true,
    basePresetId: "mopa-steel-blue-20w",
  },
  {
    id: "ss-oxide-teal",
    label: "Teal / Cyan",
    processFamily: "oxide-color",
    targetHex: "#226688",
    requiresMopa: true,
    basePresetId: "mopa-steel-teal-20w",
  },
  {
    id: "ss-oxide-green",
    label: "Green",
    processFamily: "oxide-color",
    targetHex: "#226633",
    requiresMopa: true,
    basePresetId: "mopa-steel-green-20w",
    notes: "True green on stainless is narrow-window and should be verified on scrap.",
  },
  {
    id: "ss-oxide-black",
    label: "Deep Black",
    processFamily: "oxide-black",
    targetHex: "#1a1a1a",
    requiresMopa: true,
    basePresetId: "mopa-steel-black-20w",
  },
  {
    id: "ss-engrave",
    label: "Engrave",
    processFamily: "engrave",
    basePresetId: "mopa-steel-white-20w",
    notes: "Material removal instead of oxide coloration.",
  },
] as const;

export const MATERIAL_LASER_CAPABILITIES: MaterialLaserCapability[] = [
  {
    id: "stainless-mopa-fiber",
    materialSlug: "stainless-steel",
    materialLabel: "Stainless Steel",
    laserSourceType: "fiber",
    requiresMopa: true,
    processFamilies: ["oxide-color", "oxide-black", "engrave"],
    outcomes: [...STAINLESS_MOPA_COLORS],
    notes: ["Use scrap verification when chasing color accuracy on stainless alloys."],
  },
  {
    id: "stainless-standard-fiber",
    materialSlug: "stainless-steel",
    materialLabel: "Stainless Steel",
    laserSourceType: "fiber",
    processFamilies: ["anneal-dark", "engrave"],
    outcomes: [
      {
        id: "ss-anneal-dark",
        label: "Dark Anneal",
        processFamily: "anneal-dark",
        targetHex: "#2c2c2c",
        basePresetId: "fiber-steel-black-20w",
      },
      {
        id: "ss-engrave-basic",
        label: "Engrave",
        processFamily: "engrave",
        basePresetId: "fiber-steel-white-30w",
        notes: "Standard fiber engraving on stainless needs a tuned house preset before production use.",
      },
    ],
  },
  {
    id: "titanium-mopa-fiber",
    materialSlug: "titanium",
    materialLabel: "Titanium",
    laserSourceType: "fiber",
    requiresMopa: true,
    processFamilies: ["oxide-color", "oxide-dark"],
    outcomes: [
      {
        id: "ti-oxide-color",
        label: "Oxide Color",
        processFamily: "oxide-color",
        targetHex: "#5b6eb1",
        basePresetId: "fiber-titanium-20w",
        notes: "Titanium color windows are alloy-dependent; this is a starting point only.",
      },
      {
        id: "ti-oxide-dark",
        label: "Dark Oxide",
        processFamily: "oxide-dark",
        targetHex: "#30343c",
        basePresetId: "fiber-titanium-20w",
      },
    ],
  },
  {
    id: "anodized-mopa-fiber",
    materialSlug: "anodized-aluminum",
    materialLabel: "Anodized Aluminum",
    laserSourceType: "fiber",
    requiresMopa: true,
    processFamilies: ["anodized-black-gray", "white-ablation"],
    outcomes: [
      {
        id: "anodized-black",
        label: "Rich Black",
        processFamily: "anodized-black-gray",
        targetHex: "#101010",
        requiresMopa: true,
        basePresetId: "mopa-anodized-al-20w",
      },
      {
        id: "anodized-dark-gray",
        label: "Dark Gray",
        processFamily: "anodized-black-gray",
        targetHex: "#4a4a4a",
        requiresMopa: true,
        basePresetId: "mopa-anodized-al-20w",
        parameterOverrides: {
          lineIntervalMm: 0.002,
        },
      },
      {
        id: "anodized-light-gray",
        label: "Light Gray",
        processFamily: "anodized-black-gray",
        targetHex: "#8d8d8d",
        requiresMopa: true,
        basePresetId: "mopa-anodized-al-20w",
        parameterOverrides: {
          lineIntervalMm: 0.005,
        },
      },
      {
        id: "anodized-white-ablation",
        label: "White Ablation",
        processFamily: "white-ablation",
        targetHex: "#d6d6d6",
        basePresetId: "fiber-anodized-al-20w",
      },
    ],
  },
  {
    id: "plastic-abs-fiber",
    materialSlug: "plastic-abs",
    materialLabel: "Plastic - ABS",
    laserSourceType: "fiber",
    processFamilies: ["plastic-color-change"],
    productHints: ["magazine"],
    outcomes: [
      {
        id: "abs-light-gray",
        label: "Light Gray",
        processFamily: "plastic-color-change",
        targetHex: "#8b8d92",
        basePresetId: "fiber-plastic-abs-20w",
        parameterOverrides: {
          powerPct: 32,
          speedMmS: 900,
        },
      },
      {
        id: "abs-dark-gray",
        label: "Dark Gray",
        processFamily: "plastic-color-change",
        targetHex: "#595d64",
        basePresetId: "fiber-plastic-abs-20w",
        parameterOverrides: {
          powerPct: 40,
          speedMmS: 750,
        },
      },
    ],
    notes: ["Polymer additives strongly affect contrast; confirm on the actual part before production."],
  },
  {
    id: "plastic-abs-mopa-fiber",
    materialSlug: "plastic-abs",
    materialLabel: "Plastic - ABS",
    laserSourceType: "fiber",
    requiresMopa: true,
    processFamilies: ["plastic-color-change"],
    productHints: ["magazine"],
    outcomes: [
      {
        id: "abs-light-gray",
        label: "Light Gray",
        processFamily: "plastic-color-change",
        targetHex: "#8b8d92",
        requiresMopa: true,
        basePresetId: "fiber-plastic-abs-20w",
        parameterOverrides: {
          powerPct: 30,
          speedMmS: 950,
          pulseWidthNs: 20,
        },
      },
      {
        id: "abs-dark-gray",
        label: "Dark Gray",
        processFamily: "plastic-color-change",
        targetHex: "#595d64",
        requiresMopa: true,
        basePresetId: "fiber-plastic-abs-20w",
        parameterOverrides: {
          powerPct: 40,
          speedMmS: 760,
          pulseWidthNs: 35,
        },
      },
      {
        id: "abs-black",
        label: "Black",
        processFamily: "plastic-color-change",
        targetHex: "#151515",
        requiresMopa: true,
        basePresetId: "fiber-plastic-abs-20w",
        parameterOverrides: {
          powerPct: 48,
          speedMmS: 620,
          pulseWidthNs: 60,
        },
      },
    ],
  },
  {
    id: "plastic-abs-uv",
    materialSlug: "plastic-abs",
    materialLabel: "Plastic - ABS",
    laserSourceType: "uv",
    processFamilies: ["plastic-color-change"],
    productHints: ["magazine"],
    outcomes: [
      {
        id: "abs-uv-light-gray",
        label: "Light Gray",
        processFamily: "plastic-color-change",
        targetHex: "#9a9a98",
        basePresetId: "uv-plastic-10w",
        parameterOverrides: {
          powerPct: 24,
          speedMmS: 1300,
        },
      },
      {
        id: "abs-uv-dark-gray",
        label: "Dark Gray",
        processFamily: "plastic-color-change",
        targetHex: "#5d5d59",
        basePresetId: "uv-plastic-10w",
        parameterOverrides: {
          powerPct: 34,
          speedMmS: 1100,
        },
      },
    ],
  },
  {
    id: "plastic-abs-green-diode",
    materialSlug: "plastic-abs",
    materialLabel: "Plastic - ABS",
    laserSourceType: "green-diode",
    processFamilies: ["plastic-color-change"],
    productHints: ["magazine"],
    outcomes: [
      {
        id: "abs-green-dark-gray",
        label: "Dark Gray",
        processFamily: "plastic-color-change",
        targetHex: "#5b5e66",
        notes: "Green-diode ABS support is scaffolded but no house preset exists yet.",
      },
      {
        id: "abs-green-black",
        label: "Black",
        processFamily: "plastic-color-change",
        targetHex: "#191919",
        notes: "Green-diode ABS support is scaffolded but no house preset exists yet.",
      },
    ],
  },
  {
    id: "powder-coat-co2",
    materialSlug: "powder-coat",
    materialLabel: "Powder Coat",
    laserSourceType: "co2",
    processFamilies: ["coating-ablation"],
    productHints: ["tumbler"],
    outcomes: [
      {
        id: "powder-coat-reveal",
        label: "Coating Reveal",
        processFamily: "coating-ablation",
        targetHex: "#d6d6d6",
        basePresetId: "co2-powder-coat-60w",
      },
    ],
  },
  {
    id: "powder-coat-diode",
    materialSlug: "powder-coat",
    materialLabel: "Powder Coat",
    laserSourceType: "diode",
    processFamilies: ["coating-ablation"],
    productHints: ["tumbler"],
    outcomes: [
      {
        id: "powder-coat-reveal",
        label: "Coating Reveal",
        processFamily: "coating-ablation",
        targetHex: "#d6d6d6",
        basePresetId: "diode-powder-coat-10w",
      },
    ],
  },
  {
    id: "powder-coat-fiber",
    materialSlug: "powder-coat",
    materialLabel: "Powder Coat",
    laserSourceType: "fiber",
    processFamilies: ["coating-ablation"],
    productHints: ["tumbler"],
    outcomes: [
      {
        id: "powder-coat-reveal",
        label: "Coating Reveal",
        processFamily: "coating-ablation",
        targetHex: "#d6d6d6",
        basePresetId: "mopa-powder-coat-pass1",
      },
    ],
  },
  {
    id: "painted-metal-co2",
    materialSlug: "painted-metal",
    materialLabel: "Painted Metal",
    laserSourceType: "co2",
    processFamilies: ["coating-ablation"],
    outcomes: [
      {
        id: "painted-metal-reveal",
        label: "Coating Reveal",
        processFamily: "coating-ablation",
        targetHex: "#d6d6d6",
        basePresetId: "co2-painted-metal-60w",
      },
    ],
  },
  {
    id: "cermark-steel-co2",
    materialSlug: "cermark-steel",
    materialLabel: "Stainless Steel + CerMark",
    laserSourceType: "co2",
    processFamilies: ["consumable-dark-mark"],
    outcomes: [
      {
        id: "cermark-dark-mark",
        label: "Dark Mark",
        processFamily: "consumable-dark-mark",
        targetHex: "#101010",
        basePresetId: "co2-cermark-steel-40w",
      },
    ],
  },
];

export function getMaterialLabel(materialSlug: string): string {
  return MATERIAL_LASER_CAPABILITIES.find((capability) => capability.materialSlug === materialSlug)?.materialLabel
    ?? materialSlug
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" ");
}
